name: Updraft 700hPa

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  plot_map_w_700:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libeccodes-tools libeccodes-dev
          git clone https://github.com/MeteoSwiss/opendata-nwp-demos.git
          cd opendata-nwp-demos
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-ansi

      - name: Esegui Python Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID_31: ${{ secrets.TELEGRAM_THREAD_ID_31 }}
        run: |
          # Copia, installa dipendenze e avvia
          cd opendata-nwp-demos
          pip install pytz earthkit-plots cartopy rasterio
          python ../icon_ch2_w_700.py